package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.86

import (
	"context"
	"time"

	"github.com/pranava-mohan/wikinitt/gravy/graph/model"
	"github.com/pranava-mohan/wikinitt/gravy/internal/articles"
)

// CreateCategory is the resolver for the createCategory field.
func (r *mutationResolver) CreateCategory(ctx context.Context, name string) (*model.Category, error) {
	slug, err := articles.GenerateSlug(name, 50)
	if err != nil {
		return nil, err
	}

	category, err := r.CategoryRepo.Create(ctx, name, slug)
	if err != nil {
		return nil, err
	}

	return &model.Category{
		ID:        category.ID,
		Name:      category.Name,
		Slug:      category.Slug,
		CreatedAt: category.CreatedAt.Format(time.RFC3339),
	}, nil
}

// DeleteCategory is the resolver for the deleteCategory field.
func (r *mutationResolver) DeleteCategory(ctx context.Context, id string) (bool, error) {
	err := r.CategoryRepo.Delete(ctx, id)
	if err != nil {
		return false, err
	}
	return true, nil
}

// Categories is the resolver for the categories field.
func (r *queryResolver) Categories(ctx context.Context) ([]*model.Category, error) {
	categories, err := r.CategoryRepo.List(ctx)
	if err != nil {
		return nil, err
	}

	var modelCategories []*model.Category
	for _, c := range categories {
		modelCategories = append(modelCategories, &model.Category{
			ID:        c.ID,
			Name:      c.Name,
			Slug:      c.Slug,
			CreatedAt: c.CreatedAt.Format(time.RFC3339),
		})
	}
	return modelCategories, nil
}
